---
# tasks file for app configuration

# Cloning from Source mylar repo and
# Ensure perms are cool
- name: Clone git repo
  git:
    repo: "{{ mylar_git_repo }}"
    dest: "{{ mylar_install_dir }}"
    version: master

- name: Update file perms
  file:
    path: "{{ mylar_install_dir }}"
    owner: "{{ mylar_user }}"
    group: "{{ mylar_group }}"
    recurse: yes

# We gots PIP requirements so lets install them
- name: Install pip requirements
  pip:
    requirements: "{{ mylar_install_dir }}/requirements.txt"
    executable: pip{{ python_version }}
